name: Github Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - run: CGO_ENABLED=0 go build -ldflags "-s -w"  -o kgb
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o kgb_arm64

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            kgb
            kgb_arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kgb
            kgb_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}